extends:
  - airbnb-base
  - plugin:import/errors

parser: babel-eslint

rules:
  no-console: off
  object-curly-spacing:
    - error
    - always
  array-bracket-spacing:
    - error
    - always
  template-curly-spacing:
    - error
    - always
  semi:
    - error
    - never
  comma-dangle:
    - error
    - never
  