# https://docs.codecov.io/docs/pull-request-comments
comment:
  layout: "files"
  behavior: once
  require_changes: true
  require_base: no
  require_head: yes
  branches: null

coverage:
  status:
    project: off
    patch: off
